// utils/errorTypes.js

export const ErrorTypes = {
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  API_ERROR: "API_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  AUTH_ERROR: "AUTH_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
};
